/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Play': '开始游戏',
    'New Game': '新游戏',
    'News': '动态',
    'Slot': '插槽',
    'Normal': '正常',
    'Ok': '好的',
    'Name': '名称',
    'Reset': '重置',
    'Settings': '设置',
    'Fame': '名望',
    'Effort cost': '努力成本',
    'Click for Biscuits!': '单击饼干！',
    'Change Log': '更新日志',
    'Development Log': '开发日志',
    'Fast': '快',
    'Flavor': '味道',
    'Hardtack': '硬面饼',
    'Hour': '小时',
    'Day': '天',
    'Minute': '分钟',
    'Products': '产品',
    'Qty on Hand': '现有数量',
    'Show hidden recipes': '显示隐藏的食谱',
    'Slow': '慢',
    'Storage': '存储',
    'Very Fast': '很快',
    'A game by Spinfoam Games': 'Spinfoam Games的游戏',
    'After committing to an ending, data on the Diplomacy and Station tabs would be missing until the page was refreshed; this should be fixed now.': '在选择结束后，外交和站点选项卡上的数据将会丢失，直到页面刷新;这个问题现在应该得到解决。',
    'If you are enjoying Click for Biscuits please consider supporting Spinfoam Games on Patreon or Ko-Fi if you\'re able to. Thanks and best of biscuits to you!': '如果你喜欢点击饼干，请考虑在Patreon或Ko-Fi上支持Spinfoam游戏。谢谢你，最好的饼干!',
    'Last but not least: There are new legacy skills now too! You\'ve got a handful of new options for where to spend legacy currency, each of which provide a different benefit. These new skills have high level caps too, so they should provide a lot of utility over time.': '最后但并非最不重要的是:现在也有了新的遗产技能!你有一些新的选择去哪里花费遗产货币，每一个都提供不同的好处。这些新技能也有很高的上限，因此随着时间的推移，它们应该会提供很多实用功能。',
    'Legal Info': '法律信息',
    'Disable Tips': '禁用提示',
    'display on the status bar at the top of the screen.': '显示在屏幕顶部的状态栏上。',
    'Messages': '信息',
    'Messages (': '信息 (',
    'Nice work! You\'ve unlocked the': '干得好!你已经解锁',
    'Experience (XP) is the first of five currencies you\'ll earn and spend while you Click for Biscuits.': '当你点击饼干时，经验(XP)是你将赚取和消费的五种货币中的第一种。',
    'Try making some more Hardtack -- you should unlock more features soon!': '试着做一些更硬的-你应该很快解锁更多的功能!',
    'You\'ve unlocked the XP counter': '你已经解锁了 经验计数器',
    'XP': '经验',
    'Credits': '积分',
    'Credits cost': '积分成本',
    'button to sell some Hardtack.': '按钮去出售一些硬面饼。',
    'Great. You\'ve unlocked the second currency type': '太好了。您已解锁第二种货币类型',
    'Let\'s talk about money': '让我们谈谈钱',
    'or so.': '左右。',
    's': '',
    'Try to produce and sell enough to reach': '尝试生产和销售足够达到',
    'You can earn credits by selling what you produce. Click the': '您可以通过出售自己的产品赚取积分。 点击',
    'Data Import / Export': '存档导入 / 导出',
    'Export': '导出',
    'Import': '导入',
    'Importing a game will REPLACE YOUR CURRENT GAME. Make sure that\'s what you want before you import!': '导入游戏存档将替换您当前的游戏进度。 在导入之前，请确保这是您想要的！',
    'To import a game, paste the text from a previous export into the field and click the Import button.': '要导入游戏，请将先前导出的文本粘贴到文本框中，然后单击“导入”按钮。',
    'To export your saved game, click the Export button then copy the text from the field below. This text can be imported to Click for Biscuits! on a different site or saved in a text file as a backup of your game.': '要导出游戏的存档数据，请单击“导出”按钮，然后从下面的文本框里面全选复制文本。 此文本可以导入到《点击饼干》！ 在其他网站上或保存为文本文件作为游戏存档的备份。',
    'New view unlocked!': '新视图已解锁！',
    'Resources': '资源',
    'You\'ve unlocked the Resources view! You can manage your inventory of ingredients there.\n\n                You can visit the Resources view any time by clicking on the tab at the top of the screen\n                or pressing the (2) key.': '您已经解锁了资源视图！ 您可以在那里管理原料库存。您可以随时通过单击屏幕顶部的标签或按（2）键来访问“资源”视图。',
    'button and sell them with the': '按钮并出售他们和',
    'button.': '按钮.',
    'Cost': '成本',
    'Everything you cook consumes some ingredients.': '您煮的所有东西都消耗一些食材。',
    'Flour': '面粉',
    'Infinity': '无限',
    'Keep in mind that you also have a limited storage capacity. If you don\'t have room for more ingredients\n                you won\'t be able to buy them until you free up some space.': '请记住，您的存储容量也有限。 如果您没有容纳更多食材的空间您将无法释放它们，直到您释放一些空间。',
    'Resource management': '资源管理',
    'Standard Resources': '基础资源',
    'Water': '水',
    'You can buy ingredients by clicking the': '您可以购买原料通过单击',
    'You need to keep an eye on your resources here to make sure you don\'t run out of the things you need.': '您需要在这里关注您的资源，以确保您不会用完所需的东西。',
    'Import complete!': '导入完成!',
    'Import Data': '导入存档',
    'Skills': '技能',
    'You can visit the Skills view any time by clicking on the tab at the top of the screen\n                or by pressing the (5) key.': '您可以随时通过单击屏幕顶部的标签或按（5）键来访问“技能”视图。',
    'You unlocked the Skills view. You can unlock new abilities and perks there.': '您已解锁“技能”视图。 您可以在那里解锁新技能和特权。',
    'Allows you to hire personnel to perform tasks for you': '允许您雇用人员为您执行任务',
    'and': '和',
    'Basic Management': '基础管理',
    'Learn': '学习',
    'So much to learn!': '要学的东西太多了!',
    'to unlock the Basic Management skill next.': '接下来解锁基本的管理技能。',
    'You might want to try and earn enough': '你可能会想尝试并获得足够的',
    'There are many skills to gain, but they all require you to spend some resources to learn them.\n\n                Some of the skills listed here are highlighted as Key Skills. These are the most important skills\n                you can learn -- often they will unlock whole new abilities and tools.': '有很多技能可以获得，但是它们都需要你花费一些资源来学习。这里列出的一些技能突出显示关键技能。这些是最重要的技能，你可以学习——他们常常将开启全新的技能和工具。',
    'This is a key skill; learning it will have a major impact on your experience!': '这是一项关键技能;学习它将对你的经历产生重大影响!',
    '% of the Fame you would receive by producing a food manually. You can assign cooks to various foods on the Products list.': '% 的名望获得通过手动生产食物。 您可以在“产品”列表上为各种食物分配厨师。',
    '% of the XP and': '% 的经验和',
    'and yields': '和产量',
    'button in the list below.': '按钮在下面的列表中。',
    'Cook': '厨师',
    'Cooks': '厨师',
    'Cooks can produce food for you': '厨师可以为你生产食物',
    'Cost to Hire': '雇用成本',
    'employed of': ' 最多可雇佣 ',
    'Each cook produces': '每个厨师生产',
    'Hired help': '雇用帮助',
    'Number Employed': '雇用人数',
    'Once hired, you can assign cooks to various items on the Products page.': '雇用后，您可以在“产品”页面上将厨师分配到各种项目。',
    'Personnel': '人员',
    'possible': '可能',
    'You can hire cooks by clicking the': '您可以聘请厨师通过点击',
    'You could definitely get more done if you hired some helpers.': '如果雇用一些帮手，您肯定可以完成更多工作。',
    'Don\'t cook alone': '不要一个人做饭',
    'employed,': '已雇佣，',
    'available': '可用',
    'Production': '生产',
    'You can hire cooks on the Personnel tab.': '您可以在“人员”页聘请厨师。',
    'You can now assign cooks to specific products. They will do the work of cooking the product\n                for you.\n\n                Cooks are not as skilled as you are though, so it will take them longer to cook most foods.': '您现在可以将厨师分配给特定产品。 他们将为您做饭。厨师不如您熟练，因此烹饪大多数食物将花费更长的时间。',
    'Hire chefs to increase the maximum number of cooks you can employ': '雇用厨师长以增加可以雇用的最大厨师数量',
    'shortage!': '短缺！',
    'Allows you to automate exporting products and importing resources': '使您可以自动输出产品和输入资源',
    'and allows you to create custom versions of existing recipes': '并允许您创建现有配方的自定义版本',
    'Chef': '厨师长',
    'Chefs increase the number of cooks you can employ': '厨师长增加您可以雇用的厨师数量',
    'Creativity': '创造力',
    'Enables': '启用',
    'Logistics': '后勤',
    'Adjust these values to automatically purchase resources each tick (this does not require any personnel': '调整这些值以在每笔交易时自动购买资源（这不需要任何人员',
    'and unlocks related skills': '并解锁相关技能',
    'Exports': '输出',
    'Imports': '输入',
    'Science': '科学',
    'Food Science': '食物科学',
    'Allows custom recipes to include 1 seasoning ingredient': '允许自定义食谱包括1种调味成分',
    'Allows you to make some straightforward substitutions for basic ingredients in custom recipes': '使您可以直接替换自定义配方中的基本成分',
    'Biscuit': '饼干',
    'Butter cracker': '黄油饼干',
    'Customize': '定制',
    'Discover your personal flavor': '发现你的个人口味',
    'Hide': '隐藏',
    'Nicely done! You are now able to learn new recipes and spend': '做得很好！ 您现在可以学习新食谱并花费',
    'Recipes': '食谱',
    'Scone': '烤饼',
    'to gain access to new ingredients!': '获得新成分！',
    'You can also customize existing recipes; but you\'ll need some skills in Seasoning, Filling, or Topping first.': '您还可以自定义现有食谱； 但您首先需要掌握调味，馅料或配料的一些技能。',
    'Baking Soda': '小苏打',
    'Beef': '牛肉',
    'button near an ingredient to spend': '按钮在配料旁边',
    'Carrot': '胡萝卜',
    'Chicken': '鸡肉',
    'Chicken Egg': '鸡蛋',
    'Click the': '点击',
    'Cod': '鳕鱼',
    'Expand your palate': '扩大你的味蕾',
    'Now that you have access to': '现在你可以访问',
    'Pork': '猪肉',
    'Potato': '土豆',
    'to gain access to it.': '来获得它。',
    'you can use it to unlock new ingredients.': '你可以用它来解锁新的配料。',
    '(Don\'t forget that you\'ll also need to buy some of the ingredient before you can cook with it.': '(别忘了，在你用它做菜之前，你还需要买一些原料。',
    'Base Ingredients': '基本成分',
    'Black Pepper': '黑胡椒',
    'Butter': '黄油',
    'Cancel': '取消',
    'Caraway Seeds': '香菜种子',
    'chalky': '白垩',
    'Customizing': '定制',
    'flakey': '古怪',
    'metallic': '金属',
    'Salt': '盐',
    'Recipe Name': '配方名称',
    'Save': '保存',
    'Seasonings': '调味料',
    'Select...': '选择...',
    'Sugar': '糖',
    'Toppings': '配料',
    'Wheat': '小麦',
    'You have not yet discovered this ingredient': '你还没有发现这种成分',
    ' 0 results available. Select is focused ,type to refine list, press Down to open the menu,': '0结果可用。 选择聚焦，键入以细化列表，按下箭头以打开菜单，',
    'Vanilla Extract': '香草精',
    'sweet': '甜',
    'Fame cost': '名望成本',
    'Allows a second seasoning ingredient to be added to custom recipes': '允许将第二种调味成分添加到自定义食谱中',
    'Food is an art and a science': '食物是一门艺术，也是一门科学',
    'for you, which you can spend on more advanced skills and items.': '为你，您可以在更高级的技能和项目上花费。',
    'If you want to keep expanding your skills you\'ll probably need to do some serious studying.': '如果您想继续扩大自己的技能，则可能需要认真学习。',
    'Maybe there\'s a way to have the flavor without the food...': '也许有一种方法可以不吃食物也能吃出味道……',
    'You can hire Gastropologists to produce': '您可以雇胃科医生来生产',
    'You\'re really getting the hang of this now.': '您现在真的掌握了这一点。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'There\'s also a new category of customization: Infusion. This opens up the opportunity for things like tea and coffee, but also will add a layer of customization to future recipes for things like broth and soup.': '还有一个新的定制类别:注射。这为茶和咖啡等产品提供了机会，但也将为未来的汤料配方增加一层定制化。',
    'The ability to substitute for basic ingredients (which has been part of the plan from the start) has also been implemented. You need to unlock the appropriate skills first, but you can swap out basic ingredients in many recipes now. This is a bit more complicated than just adding custom ingredients though, since the substitutions need to meet certain criteria based on the recipe.': '替代基本原料的能力(这从一开始就是计划的一部分)也得到了实施。你需要先解锁相应的技能，但是现在你可以在许多食谱中更换基本的食材。但是，这比仅仅添加自定义配料要复杂一些，因为替换需要根据菜谱满足特定的标准。',
    'This version makes some changes to how recipe customization works. Various recipes now specify what sorts of customizations they support -- so you can\'t just stuff fillings into any recipe at all anymore.': '这个版本对菜谱定制的工作方式做了一些更改。现在，各种食谱都指定了它们支持的自定义类型——因此，您再也不能将填充物塞进任何食谱中了。',
    'This is a quick update to fix a couple of especially disruptive bugs': '这是一个快速更新，以修复两个特别具有破坏性的错误',
    'The bug that caused some ingredients to produce recipes with huge (somtimes infinite) resources should be resolved.': '导致某些配料产生具有大量(有时是无限)资源的菜谱的错误应该得到解决。',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    "\n": "",
    "                ": "",
    " ": " ",
    ": ": "： ",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "               ": "",
    "Released": "发布",
    "\n": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^Seasoning (.+)$/, '调料 $1'],
    [/^Substitutions (.+)$/, '替换 $1'],
    [/^Flavor Extraction (.+)$/, '风味提取 $1'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);