/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Play': '开始游戏',
    'New Game': '新游戏',
    'News': '动态',
    'Slot': '插槽',
    'Normal': '正常',
    'Ok': '好的',
    'Name': '名称',
    'Reset': '重置',
    'Settings': '设置',
    'Fame': '名望',
    'Effort cost': '努力成本',
    'Click for Biscuits!': '点击饼干！',
    'Change Log': '更新日志',
    'Development Log': '开发日志',
    'Fast': '快',
    'Flavor': '味道',
    'Hardtack': '硬面饼',
    'Hour': '小时',
    'Day': '天',
    'Minute': '分钟',
    'Products': '产品',
    'Qty on Hand': '现有数量',
    'Show hidden recipes': '显示隐藏的食谱',
    'Slow': '慢',
    'Storage': '存储',
    'Very Fast': '很快',
    'A game by Spinfoam Games': 'Spinfoam Games的游戏',
    'After committing to an ending, data on the Diplomacy and Station tabs would be missing until the page was refreshed; this should be fixed now.': '在选择结束后，外交和站点选项卡上的数据将会丢失，直到页面刷新;这个问题现在应该得到解决。',
    'If you are enjoying Click for Biscuits please consider supporting Spinfoam Games on Patreon or Ko-Fi if you\'re able to. Thanks and best of biscuits to you!': '如果你喜欢点击饼干，请考虑在Patreon或Ko-Fi上支持Spinfoam游戏。谢谢你，最好的饼干!',
    'Last but not least: There are new legacy skills now too! You\'ve got a handful of new options for where to spend legacy currency, each of which provide a different benefit. These new skills have high level caps too, so they should provide a lot of utility over time.': '最后但并非最不重要的是:现在也有了新的遗产技能!你有一些新的选择去哪里花费遗产货币，每一个都提供不同的好处。这些新技能也有很高的上限，因此随着时间的推移，它们应该会提供很多实用功能。',
    'Legal Info': '法律信息',
    'Disable Tips': '禁用提示',
    'display on the status bar at the top of the screen.': '显示在屏幕顶部的状态栏上。',
    'Messages': '信息',
    'Messages (': '信息 (',
    'Nice work! You\'ve unlocked the': '干得好!你已经解锁',
    'Experience (XP) is the first of five currencies you\'ll earn and spend while you Click for Biscuits.': '当你点击饼干时，经验(XP)是你将赚取和消费的五种货币中的第一种。',
    'Try making some more Hardtack -- you should unlock more features soon!': '试着做一些更硬的-你应该很快解锁更多的功能!',
    'You\'ve unlocked the XP counter': '你已经解锁了 经验计数器',
    'XP': '经验',
    'Credits': '积分',
    'Credits cost': '积分成本',
    'button to sell some Hardtack.': '按钮去出售一些硬面饼。',
    'Great. You\'ve unlocked the second currency type': '太好了。您已解锁第二种货币类型',
    'Let\'s talk about money': '让我们谈谈钱',
    'or so.': '左右。',
    's': '',
    'Try to produce and sell enough to reach': '尝试生产和销售足够达到',
    'You can earn credits by selling what you produce. Click the': '您可以通过出售自己的产品赚取积分。 点击',
    'Data Import / Export': '存档导入 / 导出',
    'Export': '导出',
    'Import': '导入',
    'Importing a game will REPLACE YOUR CURRENT GAME. Make sure that\'s what you want before you import!': '导入游戏存档将替换您当前的游戏进度。 在导入之前，请确保这是您想要的！',
    'To import a game, paste the text from a previous export into the field and click the Import button.': '要导入游戏，请将先前导出的文本粘贴到文本框中，然后单击“导入”按钮。',
    'To export your saved game, click the Export button then copy the text from the field below. This text can be imported to Click for Biscuits! on a different site or saved in a text file as a backup of your game.': '要导出游戏的存档数据，请单击“导出”按钮，然后从下面的文本框里面全选复制文本。 此文本可以导入到《点击饼干》！ 在其他网站上或保存为文本文件作为游戏存档的备份。',
    'New view unlocked!': '新视图已解锁！',
    'Resources': '资源',
    'You\'ve unlocked the Resources view! You can manage your inventory of ingredients there.\n\n                You can visit the Resources view any time by clicking on the tab at the top of the screen\n                or pressing the (2) key.': '您已经解锁了资源视图！ 您可以在那里管理原料库存。您可以随时通过单击屏幕顶部的标签或按（2）键来访问“资源”视图。',
    'button and sell them with the': '按钮并出售他们和',
    'button.': '按钮.',
    'Cost': '成本',
    'Everything you cook consumes some ingredients.': '您煮的所有东西都消耗一些食材。',
    'Flour': '面粉',
    'Infinity': '无限',
    'Keep in mind that you also have a limited storage capacity. If you don\'t have room for more ingredients\n                you won\'t be able to buy them until you free up some space.': '请记住，您的存储容量也有限。 如果您没有容纳更多食材的空间您将无法释放它们，直到您释放一些空间。',
    'Resource management': '资源管理',
    'Standard Resources': '基础资源',
    'Water': '水',
    'You can buy ingredients by clicking the': '您可以购买原料通过单击',
    'You need to keep an eye on your resources here to make sure you don\'t run out of the things you need.': '您需要在这里关注您的资源，以确保您不会用完所需的东西。',
    'Import complete!': '导入完成!',
    'Import Data': '导入存档',
    'Skills': '技能',
    'You can visit the Skills view any time by clicking on the tab at the top of the screen\n                or by pressing the (5) key.': '您可以随时通过单击屏幕顶部的标签或按（5）键来访问“技能”视图。',
    'You unlocked the Skills view. You can unlock new abilities and perks there.': '您已解锁“技能”视图。 您可以在那里解锁新技能和特权。',
    'Allows you to hire personnel to perform tasks for you': '允许您雇用人员为您执行任务',
    'and': '和',
    'Basic Management': '基础管理',
    'Learn': '学习',
    'So much to learn!': '要学的东西太多了!',
    'to unlock the Basic Management skill next.': '接下来解锁基本的管理技能。',
    'You might want to try and earn enough': '你可能会想尝试并获得足够的',
    'There are many skills to gain, but they all require you to spend some resources to learn them.\n\n                Some of the skills listed here are highlighted as Key Skills. These are the most important skills\n                you can learn -- often they will unlock whole new abilities and tools.': '有很多技能可以获得，但是它们都需要你花费一些资源来学习。这里列出的一些技能突出显示关键技能。这些是最重要的技能，你可以学习——他们常常将开启全新的技能和工具。',
    'This is a key skill; learning it will have a major impact on your experience!': '这是一项关键技能;学习它将对你的经历产生重大影响!',
    '% of the Fame you would receive by producing a food manually. You can assign cooks to various foods on the Products list.': '% 的名望获得通过手动生产食物。 您可以在“产品”列表上为各种食物分配厨师。',
    '% of the XP and': '% 的经验和',
    'and yields': '和产量',
    'button in the list below.': '按钮在下面的列表中。',
    'Cook': '厨师',
    'Cooks': '厨师',
    'Cooks can produce food for you': '厨师可以为你生产食物',
    'Cost to Hire': '雇用成本',
    'employed of': ' 最多可雇佣 ',
    'Each cook produces': '每个厨师生产',
    'Hired help': '雇用帮助',
    'Number Employed': '雇用人数',
    'Once hired, you can assign cooks to various items on the Products page.': '雇用后，您可以在“产品”页面上将厨师分配到各种项目。',
    'Personnel': '人员',
    'possible': '可能',
    'You can hire cooks by clicking the': '您可以聘请厨师通过点击',
    'You could definitely get more done if you hired some helpers.': '如果雇用一些帮手，您肯定可以完成更多工作。',
    'Don\'t cook alone': '不要一个人做饭',
    'employed,': '已雇佣，',
    'available': '可用',
    'Production': '生产',
    'You can hire cooks on the Personnel tab.': '您可以在“人员”页聘请厨师。',
    'You can now assign cooks to specific products. They will do the work of cooking the product\n                for you.\n\n                Cooks are not as skilled as you are though, so it will take them longer to cook most foods.': '您现在可以将厨师分配给特定产品。 他们将为您做饭。厨师不如您熟练，因此烹饪大多数食物将花费更长的时间。',
    'Hire chefs to increase the maximum number of cooks you can employ': '雇用厨师长以增加可以雇用的最大厨师数量',
    'shortage!': '短缺！',
    'Allows you to automate exporting products and importing resources': '使您可以自动输出产品和输入资源',
    'and allows you to create custom versions of existing recipes': '并允许您创建现有配方的自定义版本',
    'Chef': '厨师长',
    'Chefs increase the number of cooks you can employ': '厨师长增加您可以雇用的厨师数量',
    'Creativity': '创造力',
    'Enables': '启用',
    'Logistics': '后勤',
    'Adjust these values to automatically purchase resources each tick (this does not require any personnel': '调整这些值以在每笔交易时自动购买资源（这不需要任何人员',
    'and unlocks related skills': '并解锁相关技能',
    'Exports': '输出',
    'Imports': '输入',
    'Science': '科学',
    'Food Science': '食物科学',
    'Allows custom recipes to include 1 seasoning ingredient': '允许自定义食谱包括1种调味成分',
    'Allows you to make some straightforward substitutions for basic ingredients in custom recipes': '使您可以直接替换自定义配方中的基本成分',
    'Biscuit': '饼干',
    'Butter cracker': '黄油饼干',
    'Customize': '定制',
    'Discover your personal flavor': '发现你的个人口味',
    'Hide': '隐藏',
    'Nicely done! You are now able to learn new recipes and spend': '做得很好！ 您现在可以学习新食谱并花费',
    'Recipes': '食谱',
    'Scone': '烤饼',
    'to gain access to new ingredients!': '获得新成分！',
    'You can also customize existing recipes; but you\'ll need some skills in Seasoning, Filling, or Topping first.': '您还可以自定义现有食谱； 但您首先需要掌握调味，馅料或配料的一些技能。',
    'Baking Soda': '小苏打',
    'Beef': '牛肉',
    'button near an ingredient to spend': '按钮在配料旁边',
    'Carrot': '胡萝卜',
    'Chicken': '鸡肉',
    'Chicken Egg': '鸡蛋',
    'Click the': '点击',
    'Cod': '鳕鱼',
    'Expand your palate': '扩大你的味蕾',
    'Now that you have access to': '现在你可以访问',
    'Pork': '猪肉',
    'Potato': '土豆',
    'to gain access to it.': '来获得它。',
    'you can use it to unlock new ingredients.': '你可以用它来解锁新的配料。',
    '(Don\'t forget that you\'ll also need to buy some of the ingredient before you can cook with it.': '(别忘了，在你用它做菜之前，你还需要买一些原料。',
    'Base Ingredients': '基本成分',
    'Black Pepper': '黑胡椒',
    'Butter': '黄油',
    'Cancel': '取消',
    'Caraway Seeds': '香菜种子',
    'chalky': '白垩',
    'Customizing': '定制',
    'flakey': '古怪',
    'metallic': '金属',
    'Salt': '盐',
    'Recipe Name': '配方名称',
    'Save': '保存',
    'Seasonings': '调味料',
    'Select...': '选择...',
    'Sugar': '糖',
    'Toppings': '配料',
    'Wheat': '小麦',
    'You have not yet discovered this ingredient': '你还没有发现这种成分',
    ' 0 results available. Select is focused ,type to refine list, press Down to open the menu,': '0结果可用。 选择聚焦，键入以细化列表，按下箭头以打开菜单，',
    'Vanilla Extract': '香草精',
    'sweet': '甜',
    'Fame cost': '名望成本',
    'Allows a second seasoning ingredient to be added to custom recipes': '允许将第二种调味成分添加到自定义食谱中',
    'Food is an art and a science': '食物是一门艺术，也是一门科学',
    'for you, which you can spend on more advanced skills and items.': '为你，您可以在更高级的技能和项目上花费。',
    'If you want to keep expanding your skills you\'ll probably need to do some serious studying.': '如果您想继续扩大自己的技能，则可能需要认真学习。',
    'Maybe there\'s a way to have the flavor without the food...': '也许有一种方法可以不吃食物也能吃出味道……',
    'You can hire Gastropologists to produce': '您可以雇胃科医生来生产',
    'You\'re really getting the hang of this now.': '您现在真的掌握了这一点。',
    'Cinnamon': '肉桂',
    'Each gastropologist produces': '每个胃科医生产生',
    'Gastropologist': '胃科医生',
    'Gastropologists produce Science': '胃科医生产生科学',
    'Milk': '牛奶',
    'Muffin': '松饼',
    'Oregano': '牛至',
    'Research Manager': '研究经理',
    'Research managers increase the number of scientists you can employ': '研究经理可以增加你可以雇佣的科学家的数量',
    'Roast Chicken': '煎鸡排',
    'Scientists': '科学家',
    'Vegetable Oil': '植物油',
    'Yellow Onion': '黄色洋葱',
    'You': '你',
    'space': '太空',
    'are': '',
    'in': '在',
    'OK': '好的',
    'Boldly consume things that have never been consumed before!': '大胆地吃一些以前从未吃过的东西!',
    'Explore new flavors and cooking techniques, seek out other civilizations, exchange food and recipes with them, and discover new delights to expand the human palette.': '探索新的口味和烹饪技术，寻找其他文明，与他们交换食物和食谱，并发现新的乐趣来扩展人类的调色板。',
    'Surprise!': '惊喜!',
    'You\'ve done well in your early days as a member of Gastrofleet, but there\'s a vast universe out there waiting to be tasted!': '作为一名美食舰队的成员，你在早期的时候做得很好，但是外面有一个广阔的宇宙等待着你去品尝!',
    'Baked Potato': '烤土豆',
    'Baking Powder': '泡打粉',
    'Beef Stew': '炖牛肉',
    'Boiled Potato': '煮土豆',
    'Brioche': '奶油蛋卷',
    'Chemical Leavening': '化学发酵',
    'Grilled Chicken': '烤鸡',
    'Linguine': '扁面条',
    'Mashed Potatoes': '土豆泥',
    'Natural Leavening': '自然发酵',
    'Pork Chop': '猪排',
    'Roasted Potato': '煎土豆',
    'Simple Steak': '简单牛排',
    'Sourdough Bagel': '酵母百吉饼',
    'Sourdough Loaf': '酵母面包',
    'Stir Fried Pork': '炒猪肉',
    'Sugar Cookie': '糖饼干',
    'Take advantage of natural microbes to leaven breads!': '利用天然微生物发酵面包!',
    'Tortilla': '玉米粉圆饼',
    'XP cost': '经验成本',
    'Use science to make things puffy': '利用科学让东西膨胀',
    'Maybe we could put food... inside other food!': '也许我们可以把食物放在其他食物里面！',
    'Nutmeg': '肉豆蔻',
    ', or': ', 或',
    'Each flavortition produces': '每种调味品都会产生',
    'Flavortitions produce a small amount of science, but can also be assigned to study unknown xeno-ingredients': '调味品产生了少量的科学，但也可以分配给研究未知的异种成分',
    'Inspire your cooks with your love of food! (Increases the effort produced by your cooks': '对食物的热爱激发您的厨师！ （增加您的厨师所付出的努力',
    'Motivational Cookery': '励志烹饪',
    'Peanut Oil': '花生油',
    'There\'s pleanty of room in there': '那里有足够的空间',
    'when studying a xeno-ingredient': '在学习异种成分时',
    'Xeno Flavortition': '异种风味',
    'Unlocks the third seasoning ingredient in custom recipes': '解锁自定义食谱中的第三个调味成分',
    'Burrito': '墨西哥卷饼',
    'Brown Sugar': '红糖',
    'Black Beans': '黑豆',
    'You\'re great at talking about food, and about yourself. (Increases the fame produced by your cooks': '您擅长谈论食物和您自己。 （增加厨师的名声',
    'Public Speaking': '公开演讲',
    'Inspiring Knife Skills': '鼓舞人心的刀技',
    'Few are as deft with a blade as you. (Increases the fame produced by your cooks': '很少有人像你一样灵巧的用刀片。(增加厨师的名气',
    'Allows you to discover at most 1 property of an ingredient by tasting it': '通过品尝，你最多可以发现一种食材的一种特性',
    'and grants access to fleet management tools': '并且授予对车队管理工具的访问权限',
    'Command & Control': '命令&控制',
    'Crew': '船员',
    'Cruiser Hull Design': '巡洋舰船体设计',
    'Discovery': '发现',
    'Each Foodship requires one captain': '每艘美食船需要一名船长',
    'Fleet': '舰队',
    'Fleet Administrator': '舰队管理员',
    'Fleet administrators allow you to hire additional crew members': '舰队管理员，让你可以雇佣更多的船员',
    'Food Writer': '美食作家',
    'Foodship Captain': '美食船长',
    'Foodship Crew Member': '美食船员',
    'Generates Fame based on the Discovery generated by a ship': '生成名望基于一艘船的发现',
    'Generates Science based on the Discovery generated by a ship': '生成科学基于一艘船的发现',
    'Goals': '目标',
    'Honey': '蜂蜜',
    'If we were to stack the food...': '如果我们把食物堆起来…',
    'Maple Syrup': '枫糖浆',
    'Mint': '薄荷',
    'Stats': '统计',
    'Stellar Gastrodynamicist': '恒星美食家',
    'We\'re going to need a bigger boat': '我们需要一艘更大的船',
    'You can\'t fly a spaceship without a crew!': '没有机组人员，您无法驾驶太空飞船！',
    'Acorn': '橡子',
    'Crew Size': '船员人数',
    'Hazelnut': '榛子',
    'Manage Fleet': '管理舰队',
    'Owned': '拥有',
    'Pelmeni': '俄罗斯饺子',
    'Ship Class': '舰船级别',
    'Ship Yard': '船坞',
    'Shuttle': '穿梭机',
    'Specialists': '专家',
    'Lemon': '柠檬',
    'Lime': '酸橙',
    'Click for Biscuits wasn\'t able to import the data you provided!': '无法导入您提供的存档数据！',
    'Are you ready to begin your delicious journey into food preparation?': '你准备好开始为你的美味之旅准备食物了吗？',
    'below to make some biscuits.': '下面做一些饼干。',
    'Let\'s get started by making some simple Hardtack. Click the hammer icon': '让我们通过做一些简单的硬面饼开始。 点击锤子图标',
    'Welcome and best of biscuits to you!': '欢迎您，最好的饼干给您！',
    'Allows all four seasoning ingredient slots to be used in custom recipes': '允许所有四个调味料插槽用于自定义配方',
    'Banana': '香蕉',
    'Basic Breadcrumbs': '基本面包屑',
    'Blueberry': '蓝莓',
    'Broccoli': '西兰花',
    'Button Mushroom': '纽扣蘑菇',
    'Delete': '删除',
    'Duck Egg': '鸭蛋',
    'Fish Cake': '鱼饼',
    'Green Grape': '绿葡萄',
    'Quail Egg': '鹌鹑蛋',
    'Red Grape': '红葡萄',
    'Sesame Oil': '芝麻油',
    'Strawberry': '草莓',
    'Xeno Resources': '异种资源',
    'A Dream Come True': '梦想成真',
    'A Hardtack Life!': '艰苦的生活！',
    'Job Creation!': '创造就业机会！',
    'Practice Makes Passable!': '熟能生巧!',
    'Achievements': '成就',
    'Active Modifiers': '主动修饰语',
    'Asparagus': '芦笋',
    'Efficient Packaging': '高效包装',
    'Endings': '结局',
    'Fame from cooks': '厨师的名气',
    'Green Beans': '青豆',
    'Green Pepper': '青椒',
    'Human': '人造',
    'Legacy': '遗物',
    'Origin': '来源',
    'Red Pepper': '红椒',
    'Smoked Salt': '烟熏盐',
    'Spinach': '菠菜',
    'Sweet Corn': '甜玉米',
    'White Cabbage': '白菜',
    "Now you've been accepted into CREMA and soon you'll have gastronomical opportunities you could only \nhave imagined a few short years ago.": "现在，您已被 CREMA 录取，很快您将拥有几年前只能想象的美食机会。",
    "There's no doubt that if you can prove yourself a skilled culinarian and leader you'll gain influence, \nresponsibilities, and access to cooking knowledge most could only dream of.": "毫无疑问，如果您能证明自己是一位熟练的烹饪师和领导者，您将获得影响力、\n责任和获得大多数人梦寐以求的烹饪知识。",
    "This is it! For your entire life you've been fascinated by cooking and by the lost history of food.": "就是这个！ 在你的一生中，你一直对烹饪和失去的食物历史着迷。",
    "Goal": "目标",
    "Keep in mind that you also have a limited storage capacity. If you don't have room for more ingredients": "请记住，您的存储容量也有限。 如果您没有空间容纳更多成分",
    "or pressing the (2) key.": "或按 (2) 键。",
    "you won't be able to buy them until you free up some space.": "在您腾出一些空间之前，您将无法购买它们。",
    "or by pressing the (5) key.": "或按 (5) 键。",
    "Some of the skills listed here are highlighted as Key Skills. These are the most important skills": "此处列出的一些技能被突出显示为关键技能。 这些是最重要的技能",
    "There are many skills to gain, but they all require you to spend some resources to learn them.": "有许多技能需要学习，但它们都需要你花费一些资源来学习它们。",
    "you can learn -- often they will unlock whole new abilities and tools.": "你可以学习——他们通常会解锁全新的能力和工具。",
    "You can visit the Skills view any time by clicking on the tab at the top of the screen": "您可以通过单击屏幕顶部的选项卡随时访问技能视图",
    "Assign cooks to produce products automatically; most recipes will take more than one tick for a cook to produce": "指派厨师自动生产产品； 大多数食谱需要一个以上的时间才能让厨师制作出来",
    "Cooks are not as skilled as you are though, so it will take them longer to cook most foods.": "厨师不像你那么熟练，所以他们需要更长的时间来烹饪大多数食物。",
    "for you.": "为你。",
    "You can now assign cooks to specific products. They will do the work of cooking the product": "您现在可以将厨师分配给特定产品。 他们将完成烹饪产品的工作",
    "A Star is Born!": "一个明星诞生了！",
    "Paycheck to Paycheck!": "薪水到薪水！",
    "Take-out Time!": "外卖时间！",
    "To-go Orders!": "外卖订单！",
    "A New Legend!": "一个新传奇！",
    "Movin' Up!": "动起来！",
    "You've done well in your early days as a member of CREMA's Gastrofleet, but there's a vast universe out there waiting to be tasted!": "作为 CREMA Gastrofleet 的一员，您在早期表现出色，但外面有一个广阔的宇宙等待品尝！",
    "Can be used as a topping": "可以作为浇头使用",
    "Effort": "努力",
    "Om-nom-knowledge!": "嗡嗡知识！",
    "option [object Object] focused, 0 of 6. 6 results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.": "选项 [object Object] 聚焦，6 个中的 0 个。6 个可用结果。 使用 Up 和 Down 选择选项，按 Enter 选择当前聚焦的选项，按 Esc 退出菜单，按 Tab 选择选项并退出菜单。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Reddit": "Reddit",
    "Ko-Fi": "Ko-Fi",
    "Twitter": "Twitter",
    "Patreon": "Patreon",
    'Hire research managers to increase the number of scientists you can employ': '雇佣研究经理来增加你可以雇佣的科学家的数量',
    'Hire fleet administrators to increase the maximum number of crew members you can employ': '雇佣舰队管理员来增加你可以雇佣的船员的最大数量',
    'Packing food more efficiently increases your storage capacity by': '更有效地包装食物可以提高存储容量',
    'When creating a custom recipe you will now only see properties from ingredients you have tasted': '创建自定义配方时，您现在将只能看到所品尝成分的特性',
    '4 new standard skills and 1 new legacy skill are now available too. (The standard skills should help out with getting a handle on storage limitations earlier in the game.': '4个新的标准技能和1个新的遗留技能现在也可用。(标准技能应该有助于在游戏早期处理存储限制。',
    'There\'s a fair bit of new content in todays update, along with some fixes and tweaks. Here are a few highlights': '在今天的更新中有很多新的内容，以及一些修正和调整。以下是一些亮点',
    'There is also a new section of the Goals tab for achievements; a new system for achievement notifications has been added as well. There are currently just a few early game achievements implemented, but more will be coming soon.': '在“目标”标签上也有一个新的“成就”部分;同时还增加了一个新的成绩通知系统。目前只有一些早期的游戏成就已经实现，但是更多的将会很快出现。',
    'There are also just a handful of new ingredients in this release, and an update to blueprints for station compartments (you\'ll now need to unlock blueprints before you can build most of the room types).': '在这个版本中还有一些新元素，还有一个对车站隔间的蓝图的更新(现在你需要解锁蓝图，然后才能建造大多数房间类型)。',
    'Second, this update adds four types of farming / ranching rooms. These rooms can be used to grow xenoingredients that you have studied. Different ingredients require different room types and different amounts of time to grow, and some particularly rare ingredients can\'t be farmed in the rooms that are currently available, but you can finally set up a production pipeline that includes xenoingredients!': '其次，这次更新增加了四种类型的农场/牧场房间。这些房间可以用来种植你研究过的异种成分。不同的食材需要不同的房间类型和不同的生长时间，一些特别稀有的食材不能在现有的房间种植，但你最终可以建立一个包含异种食材的生产流水线!',
    'A relatively small update this week that lays some ground work for some future changes. The big item of note is the addition of a detailed view on the products tab. This new view needs to be unlocked via a new skill, but it provides more information about the value of various products to different civilizations and has enough room to support new features for products in upcoming releases.': '这是一个相对较小的更新，为未来的一些变化奠定了基础。值得注意的是在products选项卡上添加了一个详细视图。这个新视图需要通过一项新技能来解锁，但是它提供了关于不同产品对不同文明的价值的更多信息，并且有足够的空间来支持即将发布的产品的新特性。',
    'A bug that was preventing the effects of Wetter Brain from being correctly applied has been fixed': '修复了阻止正确使用“湿脑”效果的错误',
    'Today\'s update adds a couple of major features that have been planned for a while now; both are related to rooms on the station.': '今天的更新增加了几个主要的功能，这些功能已经计划了一段时间了;两者都与电视台的房间有关。',
    'Today\'s update fixes a handful of bugs, notably one that affected available crew members.': '今天的更新修复了一些错误，特别是一个影响了可用的工作人员。',
    'Over the next few updates the idea of importing ingredients (and later recipes) from other civilizations will be expanding. Eventually there should also be some UI updates to help you see the impact of various civilizations\' preferences on the value of different recipes.': '在接下来的几次更新中，从其他文明进口原料(以及后来的食谱)的想法将会扩大。最后，还应该进行一些UI更新，以帮助您了解不同文明的偏好对不同菜谱价值的影响。',
    'Ingredients can now be sourced from other civilizations (this requires the new Diplomatic Agreements skill': '原料现在可以从其他文明中获得(这需要新的外交协议技能',
    'First is the ability to build a room dedicated to juicing. Once you have one (or more) of these rooms you can select an ingredient to convert in to juice. Juices tend to have flavor profiles that are similar to their source ingredients, but with some properties either emphasized or reduced.': '首先是建立一个专门用来榨汁的房间的能力。一旦你有了一个(或多个)这样的房间，你可以选择一种原料转换成果汁。果汁的口味倾向于与原料相似，但有些特性会被强调或弱化。',
    'There\'s also a new category of customization: Infusion. This opens up the opportunity for things like tea and coffee, but also will add a layer of customization to future recipes for things like broth and soup.': '还有一个新的定制类别:注射。这为茶和咖啡等产品提供了机会，但也将为未来的汤料配方增加一层定制化。',
    'The ability to substitute for basic ingredients (which has been part of the plan from the start) has also been implemented. You need to unlock the appropriate skills first, but you can swap out basic ingredients in many recipes now. This is a bit more complicated than just adding custom ingredients though, since the substitutions need to meet certain criteria based on the recipe.': '替代基本原料的能力(这从一开始就是计划的一部分)也得到了实施。你需要先解锁相应的技能，但是现在你可以在许多食谱中更换基本的食材。但是，这比仅仅添加自定义配料要复杂一些，因为替换需要根据菜谱满足特定的标准。',
    'This version makes some changes to how recipe customization works. Various recipes now specify what sorts of customizations they support -- so you can\'t just stuff fillings into any recipe at all anymore.': '这个版本对菜谱定制的工作方式做了一些更改。现在，各种食谱都指定了它们支持的自定义类型——因此，您再也不能将填充物塞进任何食谱中了。',
    'This is a quick update to fix a couple of especially disruptive bugs': '这是一个快速更新，以修复两个特别具有破坏性的错误',
    'The bug that caused some ingredients to produce recipes with huge (somtimes infinite) resources should be resolved.': '导致某些配料产生具有大量(有时是无限)资源的菜谱的错误应该得到解决。',

    //原样
    'v': 'v',
    'x': 'x',
    'QQ群号': 'QQ群号',
    'Git游戏': 'Git游戏',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    "\n": "",
    "                ": "",
    " ": " ",
    ": ": "： ",
    "Achievement complete: ": "成就完成：",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "               ": "",
    "Released": "发布",
    "\n": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^Allows you to discover up to (.+) properties of an ingredient$/, '允许您发现一种成分的最多 $1 种特性'],
    [/^(.+) new achievements$/, '$1 个新成就'],
    [/^(.+) new ingredients$/, '$1 种新的材料'],
    [/^(.+) new legacy skills$/, '$1 新的遗物技能'],
    [/^Topping (.+)$/, '配料 $1'],
    [/^Tasting (.+)$/, '品尝 $1'],
    [/^Filling (.+)$/, '馅料 $1'],
    [/^Seasoning (.+)$/, '调料 $1'],
    [/^Substitutions (.+)$/, '替换 $1'],
    [/^Flavor Extraction (.+)$/, '风味提取 $1'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);